# workers/data_loader/Dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY workers/data_loader/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common /app/common
COPY workers/app/workers
COPY workers/data_loader/data_loader.py .

CMD ["python", "data_loader.py"]
