# workers/visualization/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY workers/visualization/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common /app/common
COPY workers/app/workers
COPY workers/visualization/visualization.py .

CMD ["python", "visualization.py"]
