services:
  services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"  # RabbitMQ main communication port
      - "15673:15672" # RabbitMQ management UI
    restart: always

  worker:
    build: .
    container_name: worker
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: always # Number of workers (can be increased for scalability)

  coordinator:
    build: .
    container_name: messenger
    depends_on:
      - rabbitmq
      - worker
    command: ["python", "messenger.py"]


