#Use officical pyhton image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Install system dependencies (if needed)
RUN apt-get update && apt-get install -y \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libxi6 \
    libgtk-3-0 \
    && rm -rf /var/lib/apt/lists/*


# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Debugging: Check if pika is installed
RUN pip list | grep pika

# Copy all necessary files
COPY worker.py messenger.py /app/

#NO CMD: specified in composer.yml
