# workers/analysis/Dockerfile
FROM python:3.12 slim

WORKDIR /app

COPY workers/analysis/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common /app/common
COPY workers/app/workers
COPY workers/analysis/analysis.py .

CMD ["python", "analysis.py"]
