# workers/data_processor/Dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY workers/data_processor/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common /app/common
COPY workers/app/workers
COPY workers/data_processor/data_processor.py .

CMD ["python", "data_processor.py"]
