apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization
  template:
    metadata:
      labels:
        app: visualization
    spec:
      containers:
      - name: visualization
        image: visualization:latest  # Replace with your Docker image name
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_USER
          value: "atlas"
        - name: RABBITMQ_PASS
          value: "atlas"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
