# Dockerfile for benchmark
FROM python:3.10

WORKDIR /app

# Install dependencies
RUN pip install psutil matplotlib pandas numpy 

# Copy the benchmark scripts
COPY cpu_monitor.py /app/
COPY benchmark.py /app/

# Define environment variable
ENV DEPLOYMENT_TYPE=kubernetes

# Run benchmark.py when the container launches
CMD ["python", "benchmark.py"]
