# Use an official Python image
FROM python:3.12


WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc g++ && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY infofile.py .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "coordinator.py"]
