version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  data_worker:
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python data_worker.py
    depends_on:
      - rabbitmq

  mc_worker:
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python mc_worker.py
    depends_on:
      - rabbitmq

  aggregator:
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python analysis_aggregator.py
    depends_on:
      - rabbitmq
    ports:
      - "8888:8888"  # Optional for Jupyter

  task_sender:
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python /app/send_tasks.py --test full
    depends_on:
      - rabbitmq
    networks:
      - default
